### ISSUE TITLE
"Could not find a version that satisfies the requirement gdax_recurring (from versions: )"

### ISSUE THREAD

**Issue by ghost** [landakram/hodl-cli#1]
I just tried installing your script and it seems pip can't find it. Am I doing something wrong?

The error:
```
Could not find a version that satisfies the requirement gdax_recurring (from versions: )
No matching distribution found for gdax_recurring
```

**Comment by landakram** [comment]
Hey @davidpgil! Thanks for the report. This was probably happening because you were using Python >= 3, and this package was only published for Python 2.x.x. 

I just published a new version that's compatible with Python 3 as well as Python 2: https://pypi.python.org/pypi/gdax-recurring/

Enjoy!
